# Generated by Django 4.2.5 on 2024-01-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_billing_claim_document_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_type',
        ),
    ]
