# Generated by Django 4.2.5 on 2024-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_remove_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
